import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:mobx/mobx.dart';

part 'connectivity_store.g.dart'; // This will be generated by build_runner

class ConnectionStore = _ConnectionStore with _$ConnectionStore;

abstract class _ConnectionStore with Store {
  @observable
  ConnectivityResult _connectivityResult = ConnectivityResult.none;

  @computed
  bool get isConnected => _connectivityResult != ConnectivityResult.none;

  @action
  Future<void> initConnectivity() async {
    final result = await Connectivity().checkConnectivity();
    _connectivityResult = result.first;
  }

  @action
  void onConnectivityChanged(ConnectivityResult result) {
    _connectivityResult = result;
  }
}
