import 'package:mobx/mobx.dart';
import 'package:sample_bank/utility/api_repository.dart';

import '../model/posts_response.dart';

part 'posts_store.g.dart'; // This will be generated by build_runner

class PostStore = _PostStore with _$PostStore;

abstract class _PostStore with Store {
  final ApiRepository _apiRepository;

  _PostStore(this._apiRepository);

  @observable
  ObservableList<Post> posts = ObservableList<Post>();

  @observable
  bool isLoading = false;

  @observable
  String? errorMessage;

  @action
  Future<void> fetchPosts() async {
    isLoading = true;
    errorMessage = null;

    try {
      final allPosts = await _apiRepository.fetchAllPosts();
      posts.clear();
      posts.addAll(allPosts);
    } catch (e) {
      errorMessage = 'Error fetching posts: $e';
    } finally {
      isLoading = false;
    }
  }
}
