import 'package:mobx/mobx.dart';

part 'send_money_store.g.dart'; // This will be generated by build_runner

class SendMoneyStore = _SendMoneyStore with _$SendMoneyStore;

abstract class _SendMoneyStore with Store {
  @observable
  bool isVisible = false;

  @action
  void toggleVisibility() {
    isVisible = !isVisible;
  }
}
